=== Paula-Elorrieta/XML-Ariketak/III ariketak/ikasleak3.xsd
<?xml version="1.0" encoding="UTF-8"?>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <xs:element name="ikasleak">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="ikaslea" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="nan" type="xs:integer"></xs:element>
                                <xs:element name="izena" type="xs:string"></xs:element>
                                <xs:element name="helbidea">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="kalea" type="xs:string"></xs:element>
                                            <xs:element name="zbk" type="xs:integer"></xs:element>
                                            <xs:element name="herria" type="xs:string"></xs:element>
                                            <xs:element name="probintzia" type="xs:string"></xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="telefonoa" type="xs:integer" maxOccurs="2"></xs:element>
                                <xs:element name="eposta" type="xs:string" minOccurs="0"></xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
    </xs:schema>

=== Paula-Elorrieta/XML-Ariketak/III ariketak/ikasleak3.xml
<?xml version="1.0" encoding="UTF-8"?>
<ikasleak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ikasleak3.xsd">
    <ikaslea>
        <nan>11111111</nan>
        <izena>Iraide Etxeberria</izena>
        <helbidea>
            <kalea>Kale nagusia</kalea>
            <zbk>5</zbk>
            <herria>Bilbao</herria>
            <probintzia>Bizkaia</probintzia>
        </helbidea>
        <telefonoa>944000000</telefonoa>
    </ikaslea>
    <ikaslea>
        <nan>22222222</nan>
        <izena>Joseba Mikel Zarraga</izena>
        <helbidea>
            <kalea>Gorbeia</kalea>
            <zbk>75</zbk>
            <herria>Artea</herria>
            <probintzia>Bizkaia</probintzia>
        </helbidea>
        <telefonoa>944999999</telefonoa>
        <telefonoa>564654243</telefonoa>
        <eposta>joseba@gmail.com</eposta>
    </ikaslea>
</ikasleak>
